// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLiiwKOqocyj_o1XjTGdwdfxkASfm6km4',
    appId: '1:558684784283:web:d8ac32e47b73d65f04e83e',
    messagingSenderId: '558684784283',
    projectId: 'judgement-2fdfa',
    authDomain: 'judgement-2fdfa.firebaseapp.com',
    databaseURL: 'https://judgement-2fdfa-default-rtdb.firebaseio.com',
    storageBucket: 'judgement-2fdfa.firebasestorage.app',
    measurementId: 'G-17XHKQBSQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPrBgrTez2CeMt-x6Pyc6PWR8XYMIOQQ',
    appId: '1:558684784283:android:a13586b3dfe60a1f04e83e',
    messagingSenderId: '558684784283',
    projectId: 'judgement-2fdfa',
    databaseURL: 'https://judgement-2fdfa-default-rtdb.firebaseio.com',
    storageBucket: 'judgement-2fdfa.firebasestorage.app',
  );
}
